trigger: none

pool:
  vmImage: 'ubuntu-22.04'

parameters:
- name: neoloadApiUrl
  type: string
  default: 'https://neoload-api.saas.neotys.com/'
- name: neoloadToken
  type: string
  default: 'c47c62c1ad529e0baf86dbc01544dd3749398a46a3026fcb'
- name: zoneId
  type: string
  default: 'jlREk'

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test from Azure Devops
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --version

  - task: Bash@3
    displayName: Configure the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload login --url ${{parameters.neoloadApiUrl}} ${{parameters.neoloadToken}} \
                test-settings --zone ${{parameters.zoneId}} --scenario "Scenario 1 - Ramp Up (Slow)" \
                use "70f1982b-0612-494d-a702-306f6abc9bab"

  - task: Bash@3
    displayName: Run the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload run

  - task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
